---

- name: Get NASR Interfaces
  hosts: No_ASR
  connection: local
  gather_facts: false

#  vars_prompt:
 #   - name: "username"
  #  - name: "password"

#  vars:
 #   cli:
  #    host: "{{ inventory_hostname }}"
   #   username: "{{ username }}"
    #  password: "{{ password }}"

  tasks:
   - name: OBTAIN LOGIN CREDENTIALS
     include_vars: secrets.yml

   - name: DEFINE PROVIDER
     set_fact:
      provider:
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"

   - name: Get NASR Interfaces
     ios_command:
      authorize: yes
      provider: "{{ provider }}"
      commands:
        - show interfaces status

     register: result

   - local_action:
       copy content={{ result.stdout[0] }}
       dest=/applis/dcs/a468850/output/sh_int_status_{{ inventory_hostname }}.txt

