---

- name: Get shared services Inventory
  hosts: all
  connection: local
  gather_facts: false


  tasks:
   - name: Obtain credentials
     include_vars: password.yml

   - name: Define provider
     set_fact:
      provider:
        username: "{{ creds['username'] }}"
        password: "{{ creds['password'] }}"

   - name: Get shared services Inventory
     nxos_command:

      provider: "{{ provider }}"
      commands:
        - show inventory

     register: result

   - local_action:
       copy content={{ result.stdout[0] }}
       dest=/applis/dcs/a468850/output/sh_inv_{{ inventory_hostname }}
   - name: parsing
     shell: /applis/dcs/tools/python/bin/python3.6 /applis/dcs/a468850/playbooks/templates/my_textfsm.py  /applis/dcs/a468850/playbooks/templates/cisco_nxos_show_inventory.template /applis/dcs/a468850/output/sh_inv_{{ inventory_hostname }}
     with_items: "{{ result.stdout[0] }}"
   - name: Move directory
     shell: mv /applis/dcs/a468850/output/sh_inv_{{ inventory_hostname }}.csv /applis/dcs/a468850/shared_services/inventory/
     
   - name: cleaning
     file:
       path: /applis/dcs/a468850/output/sh_inv_{{ inventory_hostname }}
       state: absent



